### PR TITLE
adding sm64js to the projects list

### PR DESCRIPTION
**Pull request by sm64js**

### CODE REVIEW

**Comment by jeremyckahn** [comment]
Nice! Thank you @sm64js! I'm proud to feature this awesome project. 😃

**Comment by github10omar** [comment]
can i try suggesting ideas for the game?
idk github but i like to support it

**Comment by jeremyckahn** [comment]
Hi @github10omar, GitHub is a platform for developers to build software projects such as @sm64js, which I didn't develop. The project you left a comment on is Keydrown, a project that I made that is used by @sm64js. If you'd like to suggest an idea for sm64js, you'll want to [head over to the Issues page for that project](https://github.com/sm64js/sm64js/issues) and leave a comment there.

Good luck!

**Comment by github10omar** [comment]
Thanks!

**Pull request merged**
