### PR TITLE
add TILDE and TAB keys

### PR DESCRIPTION
**Pull request by kevzettler**
Adds Tilde and Tab keys. Any reason these were not in the list?

Bumps dependencies because ~node_modules~ was failing to install. 
One of the grunt tools was trying to install phantomJS which is no longer available.

### CODE REVIEW

**Comment by jeremyckahn** [comment]
This looks great, thanks for adding these mappings @kevzettler! There's no real reason these keys were omitted; it probably just didn't occur to me to add them.

Just one thing before merging this — what do you think about removing the `yarn.lock` file? I realize that it's a best practice to include it, but I don't really have the bandwidth to validate it myself. So, I would prefer to just leave it out in the interest of being confident about the dependencies this project is using.

Also, sorry the toolchain is so outdated! I haven't really needed to work on this project once I got it stable. 😅

**Comment by kevzettler** [comment]
yarn.lock removed in https://github.com/jeremyckahn/keydrown/pull/14/commits/7cac54e7cb8fe6bd995a2c19f59230be86fe9cef

**Comment by jeremyckahn** [comment]
Thanks for making that change, @kevzettler! I will pull this down and give it a proper review and merge once I have some time to do so — hopefully in the next day or so.

**Comment by kevzettler** [comment]
thanks @jeremyckahn let me know if it needs any other updates.

**Comment by jeremyckahn** [comment]
This has been [released as 1.2.4](https://github.com/jeremyckahn/keydrown/releases/tag/1.2.4). Thanks again for the contribution, @kevzettler!

**Pull request merged**
