### PR TITLE
Pass time delta to kd.run (#9).

### PR DESCRIPTION
**Pull request by jeremyckahn**
Implements `kd.run` callback time deltas.  The delta is provided as the first parameter to the `kd.run` callback.

@jcmiller11, please review this PR.  To test it, clone out this branch, update the dependencies with `npm install` (I recently updated the version of Uglify that was being used), and run `grunt build` to generate the `dist` files.

### CODE REVIEW

**Comment by jcmiller11** [comment]
Sorry I haven't had a chance to test this yet, but just wondering, does this work within the press functions?  Like kd.SPACE.press(function (dt) {console.log(dt)}

**Comment by jeremyckahn** [comment]
That isn't how I set this up, no.  The significant function to track the deltas of is `run`, so the delta time is only provided to `run`'s callback.  I don't want to propagate that data down to each key's handler function, as Keydrown cannot guarantee its accuracy because `down` and `up` handlers can be called programmatically outside of the `run` loop.  The downstream application code would have to handle propagating that data as necessary.

**Comment by jcmiller11** [comment]
Alright, unfortunately my application already was using it's own run loop so I'm going to have to refactor it a little to use keydrown's run to test this.  Give me a day or two and I'll get back to you

**Comment by jeremyckahn** [comment]
Sounds good.  Sorry about the extra work, but I want to keep Keydrown focused, simple, and predictable.  Thanks for being flexible!

**Comment by jcmiller11** [comment]
Tested and it works perfectly for me.  It's too bad there isn't a simpler way to have it available in the down/up/press functions but for now I guess if someone wants to use keydrown for games they can simply implement the key controls by checking isDown from within their kd.run loop.

**Comment by jeremyckahn** [comment]
Great, thanks for testing!  I will merge and release this change when I have a moment to do so.

**Comment by jcmiller11** [comment]
Thanks for adding the feature!  I have been super busy this week otherwise I would have looked into implementing it myself.  I'll dive into your source when I have the time and see about coming up with a way to implement it for the other functions.  If it ends up making things less than focused, simple, and predictable I'll make sort of a separate "game-dev focused" fork.

**Comment by jeremyckahn** [comment]
Released as [1.2.2](https://github.com/jeremyckahn/keydrown/releases/tag/1.2.2).  Thanks again for filing the ticket, and let me know if you decide to fork!

**Pull request merged**
